// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteBancoMaster.Infra.Data;

#nullable disable

namespace TesteBancoMaster.Infra.Migrations
{
    [DbContext(typeof(ViagensContext))]
    [Migration("20220703181850_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TesteBancoMaster.Infra.Entities.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorPassagem")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("viagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destino = "BRC",
                            Origem = "GRU",
                            ValorPassagem = 10m
                        },
                        new
                        {
                            Id = 2,
                            Destino = "SCL",
                            Origem = "BRC",
                            ValorPassagem = 5m
                        },
                        new
                        {
                            Id = 3,
                            Destino = "CDG",
                            Origem = "GRU",
                            ValorPassagem = 75m
                        },
                        new
                        {
                            Id = 4,
                            Destino = "SCL",
                            Origem = "GRU",
                            ValorPassagem = 20m
                        },
                        new
                        {
                            Id = 5,
                            Destino = "ORL",
                            Origem = "GRU",
                            ValorPassagem = 56m
                        },
                        new
                        {
                            Id = 6,
                            Destino = "CDG",
                            Origem = "ORL",
                            ValorPassagem = 5m
                        },
                        new
                        {
                            Id = 7,
                            Destino = "ORL",
                            Origem = "SCL",
                            ValorPassagem = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
